# Risk Mining Pipeline Configuration

data:
  desired_data: ["sind-tj"]
  data_dirs:
    sind: "~/datasets/SinD_dataset"
  desired_dt: 0.1

rules:
  spatial:
    in_roi:
      enabled: true
      roi_radius: 50.0
  dynamic:
    ttc:
      enabled: true
      ttc_threshold: 2.5

slicer:
  pre_buffer_sec: 2.0
  post_buffer_sec: 2.0

output:
  output_dir: "./output"
